### ISSUE TITLE
Implementing "Improvements to Requests 2.0"

### ISSUE THREAD

**Issue by schmidsi** [feinheit/django-facebook-graph#4]
Facebook will change the way requests work on 1.1.2012. Especially the JavaScript result.

http://developers.facebook.com/blog/post/569/

**Comment by sbaechler** [comment]
Facebook apparently already forces the change on new apps:
Starting today new apps will automatically be opted into “Upgrade to Requests 2.0” and “Requests 2.0 Efficient" 

The new requests are much better.

We should create a new Class EfficientRequest or something like that for backwards compatibility. To is now a M2M field.

**Comment by schmidsi** [comment]
agree. maybe we can aso write a migration.

**Comment by sbaechler** [comment]
Definitely. I think Request2 would be easier than EfficientRequest.

**Comment by sbaechler** [comment]
I tried a version with a string-id of the format <Request-id>_<TO_ID>. This way it can be queried directly from Facebook and we get the to field as well. But this imposes two problems: When a receiver opens the app the requests-ids that are in the signed request are just the request-ids. Because a request can have multiple receivers we cannot use id_startswith.
I'll try another approach: Make the _to field optional. Maybe a M2M. It's not really needed because it is usually the current user. And leave the id the integer that stores the request_id.
We also need a function to delete the requests on Facebook. Maybe using a count field?

**Comment by sbaechler** [comment]
A new approach: leave the id as BigInt. the _to field is optional. I changed the delete method so it can delete the correct app request on facebook if the current user is known. The _to field should be equal to the current user. That's why you should ignore it's status when reading the object from the database and update the field in a view.
